"""initial_schema

Revision ID: bd152577552d
Revises:
Create Date: 2026-02-11 15:35:58.567360

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd152577552d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('monthly_budget_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('organization_id', 'key', name='uq_settings_organization_id_key')
    )
    op.create_index('idx_settings_org_key', 'settings', ['organization_id', 'key'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='user_role'), server_default='editor', nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_organization', 'users', ['organization_id'], unique=False)
    op.create_table('api_usage',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.Enum('claude', 'whisper', 'resend', name='api_service'), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_usage_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_usage_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage'))
    )
    op.create_index('idx_api_usage_org_date', 'api_usage', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_api_usage_service', 'api_usage', ['service', 'created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("token_type IN ('email_verify', 'password_reset')", name=op.f('ck_auth_tokens_token_type_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index('idx_auth_tokens_hash', 'auth_tokens', ['token_hash'], unique=False, postgresql_where='used_at IS NULL')
    op.create_table('goals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('type', sa.Enum('predefined', 'custom', name='goal_type'), server_default='custom', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_goals_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_goals_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index('idx_goals_organization', 'goals', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='read_at IS NULL')
    op.create_table('journeys',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='journey_status'), server_default='active', nullable=False),
    sa.Column('perspectives_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('perspectives_completed BETWEEN 0 AND 12', name=op.f('ck_journeys_perspectives_completed_range')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_journeys_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_journeys_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys'))
    )
    op.create_index('idx_journeys_organization', 'journeys', ['organization_id'], unique=False)
    op.create_index('idx_journeys_status', 'journeys', ['organization_id', 'status'], unique=False)
    op.create_table('perspectives',
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Enum('architecture', 'design', 'engineering', name='dimension_type'), nullable=False),
    sa.Column('phase', sa.Enum('generate', 'review', 'validate', 'summarize', name='phase_type'), nullable=False),
    sa.Column('status', sa.Enum('locked', 'pending', 'in_progress', 'completed', name='perspective_status'), server_default='locked', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_perspectives_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perspectives')),
    sa.UniqueConstraint('journey_id', 'dimension', 'phase', name='uq_perspectives_journey_dimension_phase')
    )
    op.create_index('idx_perspectives_journey', 'perspectives', ['journey_id'], unique=False)
    op.create_index('idx_perspectives_status', 'perspectives', ['journey_id', 'status'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='claude-haiku-4-5-20251001', nullable=False),
    sa.Column('system_prompt_version', sa.String(length=20), server_default='v1', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_name IN ('lyra','mira','dex','rex','vela','koda','halo','nova','axiom')", name=op.f('ck_agent_sessions_agent_name_check')),
    sa.CheckConstraint('input_tokens >= 0', name=op.f('ck_agent_sessions_input_tokens_nonneg')),
    sa.CheckConstraint('output_tokens >= 0', name=op.f('ck_agent_sessions_output_tokens_nonneg')),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_agent_sessions_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    op.create_index('idx_agent_sessions_agent', 'agent_sessions', ['agent_name', 'created_at'], unique=False)
    op.create_index('idx_agent_sessions_cost', 'agent_sessions', ['created_at', 'cost_cents'], unique=False)
    op.create_index('idx_agent_sessions_perspective', 'agent_sessions', ['perspective_id'], unique=False)
    op.create_table('bank_instances',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('bankable', 'film', 'film_reel', 'published', name='bank_type'), nullable=False),
    sa.Column('synopsis', sa.Text(), server_default='', nullable=False),
    sa.Column('decision_audit', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('documents_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vibes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('emails_sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('feedback_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('agent_assessments', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('documents_count >= 0', name=op.f('ck_bank_instances_documents_count_nonneg')),
    sa.CheckConstraint('emails_sent >= 0', name=op.f('ck_bank_instances_emails_sent_nonneg')),
    sa.CheckConstraint('feedback_received >= 0', name=op.f('ck_bank_instances_feedback_received_nonneg')),
    sa.CheckConstraint('vibes_count >= 0', name=op.f('ck_bank_instances_vibes_count_nonneg')),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_bank_instances_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_instances'))
    )
    op.create_index('idx_bank_instances_perspective', 'bank_instances', ['perspective_id'], unique=False)
    op.create_index('idx_bank_instances_type', 'bank_instances', ['type'], unique=False)
    op.create_table('documents',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('minio_key', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size > 0', name=op.f('ck_documents_file_size_positive')),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_documents_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('minio_key', name=op.f('uq_documents_minio_key'))
    )
    op.create_index('idx_documents_perspective', 'documents', ['perspective_id'], unique=False)
    op.create_table('email_log',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), server_default='stakeholder', nullable=False),
    sa.Column('template_type', sa.Enum('stakeholder_invite', 'vibe_summary', 'journey_complete', 'vdba_published', 'budget_alert', name='email_template'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('resend_message_id', sa.String(length=100), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delivery_status IN ('sent', 'delivered', 'bounced', 'failed')", name=op.f('ck_email_log_delivery_status_check')),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_email_log_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_email_log_sent_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_log'))
    )
    op.create_index('idx_email_log_perspective', 'email_log', ['perspective_id'], unique=False)
    op.create_table('vibe_sessions',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('conducted_by', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('audio_minio_key', sa.String(length=1000), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('transcript_minio_key', sa.String(length=1000), nullable=True),
    sa.Column('transcription_cost_cents', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='transcribing', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('transcribing', 'analyzing', 'complete', 'failed')", name=op.f('ck_vibe_sessions_vibe_status_check')),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_vibe_sessions_duration_seconds_positive')),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], name=op.f('fk_vibe_sessions_conducted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_vibe_sessions_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vibe_sessions')),
    sa.UniqueConstraint('audio_minio_key', name=op.f('uq_vibe_sessions_audio_minio_key'))
    )
    op.create_index('idx_vibe_sessions_perspective', 'vibe_sessions', ['perspective_id'], unique=False)
    op.create_table('axiom_challenges',
    sa.Column('perspective_id', sa.UUID(), nullable=False),
    sa.Column('challenge_text', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='challenge_severity'), nullable=False),
    sa.Column('targeted_agents', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('evidence_needed', sa.Text(), server_default='', nullable=False),
    sa.Column('resolution', sa.Enum('resolved', 'accepted_risk', 'action_required', name='challenge_resolution'), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_axiom_challenges_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['perspective_id'], ['perspectives.id'], name=op.f('fk_axiom_challenges_perspective_id_perspectives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_axiom_challenges'))
    )
    op.create_index('idx_axiom_challenges_perspective', 'axiom_challenges', ['perspective_id'], unique=False)
    op.create_index('idx_axiom_challenges_unresolved', 'axiom_challenges', ['perspective_id'], unique=False, postgresql_where='resolution IS NULL')
    op.create_table('vdbas',
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('bank_instance_id', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('export_url', sa.String(length=1000), nullable=True),
    sa.Column('export_format', sa.String(length=10), server_default='pdf', nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("export_format IN ('pdf', 'docx', 'json')", name=op.f('ck_vdbas_export_format_check')),
    sa.ForeignKeyConstraint(['bank_instance_id'], ['bank_instances.id'], name=op.f('fk_vdbas_bank_instance_id_bank_instances')),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_vdbas_journey_id_journeys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vdbas_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vdbas'))
    )
    op.create_index('idx_vdbas_journey', 'vdbas', ['journey_id'], unique=False)
    op.create_index('idx_vdbas_organization', 'vdbas', ['organization_id'], unique=False)
    op.create_table('vibe_analyses',
    sa.Column('vibe_session_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), server_default='post_vibe', nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_vibe_analyses_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['vibe_session_id'], ['vibe_sessions.id'], name=op.f('fk_vibe_analyses_vibe_session_id_vibe_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vibe_analyses')),
    sa.UniqueConstraint('vibe_session_id', 'agent_name', 'analysis_type', name='uq_vibe_analyses_session_agent_type')
    )
    op.create_index('idx_vibe_analyses_session', 'vibe_analyses', ['vibe_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vibe_analyses_session', table_name='vibe_analyses')
    op.drop_table('vibe_analyses')
    op.drop_index('idx_vdbas_organization', table_name='vdbas')
    op.drop_index('idx_vdbas_journey', table_name='vdbas')
    op.drop_table('vdbas')
    op.drop_index('idx_axiom_challenges_unresolved', table_name='axiom_challenges', postgresql_where='resolution IS NULL')
    op.drop_index('idx_axiom_challenges_perspective', table_name='axiom_challenges')
    op.drop_table('axiom_challenges')
    op.drop_index('idx_vibe_sessions_perspective', table_name='vibe_sessions')
    op.drop_table('vibe_sessions')
    op.drop_index('idx_email_log_perspective', table_name='email_log')
    op.drop_table('email_log')
    op.drop_index('idx_documents_perspective', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_bank_instances_type', table_name='bank_instances')
    op.drop_index('idx_bank_instances_perspective', table_name='bank_instances')
    op.drop_table('bank_instances')
    op.drop_index('idx_agent_sessions_perspective', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_cost', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_agent', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('idx_perspectives_status', table_name='perspectives')
    op.drop_index('idx_perspectives_journey', table_name='perspectives')
    op.drop_table('perspectives')
    op.drop_index('idx_journeys_status', table_name='journeys')
    op.drop_index('idx_journeys_organization', table_name='journeys')
    op.drop_table('journeys')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where='read_at IS NULL')
    op.drop_table('notifications')
    op.drop_index('idx_goals_organization', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_auth_tokens_hash', table_name='auth_tokens', postgresql_where='used_at IS NULL')
    op.drop_table('auth_tokens')
    op.drop_index('idx_api_usage_service', table_name='api_usage')
    op.drop_index('idx_api_usage_org_date', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index('idx_users_organization', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_settings_org_key', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
